- name: Sample 
  hosts: all
  tasks:
    - name: Get the host detail 
      shell: 'echo $(hostname -i)'
      register: host
    - name: Print the value 
      debug: msg="The Host is {{ host.stdout }}" 
