---
- hosts: all
  become: true
  vars:
    packages: [ 'vim', 'git', 'curl' ]
  tasks:
  - name: Install Package
    yum: name={{ item }} state=latest
    with_items: packages
  - name: Install httpd Package
    yum: name=httpd state=latest
