---
- hosts: all
  become: true
  tasks:
  - name: Install Package
    yum: name={{ item }} state=latest
    with_items:
    - vim
    - git
    - curl
  - name: Install httpd Package
    yum: name=httpd state=latest
